import { NavbarDemo } from '@/components/home/navbar'
import QueryProviders from '@/components/shared/tanstack-provider'
import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section className="relative w-full h-full ">
      <QueryProviders>
        <ViewTransitions>
          <NavbarDemo />
          {children}
        </ViewTransitions>
      </QueryProviders>
    </section>
  )
}
