import { NavbarDemo } from '@/components/home/navbar'
import QueryProviders from '@/components/shared/tanstack-provider'
import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

export const metadata: Metadata = {
  title: 'Medical App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section className="relative w-full h-full ">
      <NuqsAdapter>
        <QueryProviders>
          <ViewTransitions>
            <NavbarDemo />
            {children}
          </ViewTransitions>
        </QueryProviders>
      </NuqsAdapter>
    </section>
  )
}
